{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "91af2116-cf1f-452f-bf89-7a8227f374e8",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "' Here are a few reasons why using the Exception class as the base class for custom exceptions is beneficial:\\n\\nStandardized Interface: The Exception class defines common methods and attributes that are used to handle and \\nprocess exceptions, such as __str__() for obtaining a string representation of the exception and args for accessing\\nthe exception arguments. By inheriting from Exception, your custom exception automatically inherits these methods \\nand attributes, providing a consistent interface with other exceptions.\\n\\nCompatibility with Exception Handling: In Python, exception handling mechanisms, such as try-except blocks, are \\ndesigned to work with instances of the Exception class or its subclasses. By inheriting from Exception, your \\ncustom exception can be caught and handled using the same mechanisms, allowing for consistent and predictable \\nexception handling in your code.\\n\\nException Hierarchy: The Exception class is the root of the built-in exception hierarchy in Python. By inheriting \\nfrom Exception, you can create a well-organized and structured hierarchy of exceptions specific to your application\\nor problem domain. This can help in categorizing and handling different types of exceptions in a more granular and\\nmeaningful way.\\n\\nCode Readability and Maintainability: When you use the Exception class as the base class for custom exceptions, it\\nimproves the readability and maintainability of your code. Other developers familiar with Python conventions will\\neasily recognize and understand that your custom class is an exception, enabling them to handle it appropriately.'"
      ]
     },
     "execution_count": 1,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# 1st-\n",
    "''' Here are a few reasons why using the Exception class as the base class for custom exceptions is beneficial:\n",
    "\n",
    "Standardized Interface: The Exception class defines common methods and attributes that are used to handle and \n",
    "process exceptions, such as __str__() for obtaining a string representation of the exception and args for accessing\n",
    "the exception arguments. By inheriting from Exception, your custom exception automatically inherits these methods \n",
    "and attributes, providing a consistent interface with other exceptions.\n",
    "\n",
    "Compatibility with Exception Handling: In Python, exception handling mechanisms, such as try-except blocks, are \n",
    "designed to work with instances of the Exception class or its subclasses. By inheriting from Exception, your \n",
    "custom exception can be caught and handled using the same mechanisms, allowing for consistent and predictable \n",
    "exception handling in your code.\n",
    "\n",
    "Exception Hierarchy: The Exception class is the root of the built-in exception hierarchy in Python. By inheriting \n",
    "from Exception, you can create a well-organized and structured hierarchy of exceptions specific to your application\n",
    "or problem domain. This can help in categorizing and handling different types of exceptions in a more granular and\n",
    "meaningful way.\n",
    "\n",
    "Code Readability and Maintainability: When you use the Exception class as the base class for custom exceptions, it\n",
    "improves the readability and maintainability of your code. Other developers familiar with Python conventions will\n",
    "easily recognize and understand that your custom class is an exception, enabling them to handle it appropriately.'''\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "741e2e7c-9048-47be-aed5-79af99fac3cc",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception\n",
      "    TypeError\n",
      "        FloatOperation\n",
      "        MultipartConversionError\n",
      "    StopAsyncIteration\n",
      "    StopIteration\n",
      "    ImportError\n",
      "        ModuleNotFoundError\n",
      "        ZipImportError\n",
      "    OSError\n",
      "        ConnectionError\n",
      "            BrokenPipeError\n",
      "            ConnectionAbortedError\n",
      "            ConnectionRefusedError\n",
      "            ConnectionResetError\n",
      "                RemoteDisconnected\n",
      "        BlockingIOError\n",
      "        ChildProcessError\n",
      "        FileExistsError\n",
      "        FileNotFoundError\n",
      "        IsADirectoryError\n",
      "        NotADirectoryError\n",
      "        InterruptedError\n",
      "            InterruptedSystemCall\n",
      "        PermissionError\n",
      "        ProcessLookupError\n",
      "        TimeoutError\n",
      "        UnsupportedOperation\n",
      "        itimer_error\n",
      "        herror\n",
      "        gaierror\n",
      "        SSLError\n",
      "            SSLCertVerificationError\n",
      "            SSLZeroReturnError\n",
      "            SSLWantWriteError\n",
      "            SSLWantReadError\n",
      "            SSLSyscallError\n",
      "            SSLEOFError\n",
      "        Error\n",
      "            SameFileError\n",
      "        SpecialFileError\n",
      "        ExecError\n",
      "        ReadError\n",
      "        URLError\n",
      "            HTTPError\n",
      "            ContentTooShortError\n",
      "        BadGzipFile\n",
      "    EOFError\n",
      "        IncompleteReadError\n",
      "    RuntimeError\n",
      "        RecursionError\n",
      "        NotImplementedError\n",
      "            ZMQVersionError\n",
      "            StdinNotImplementedError\n",
      "        _DeadlockError\n",
      "        BrokenBarrierError\n",
      "        BrokenExecutor\n",
      "            BrokenThreadPool\n",
      "        SendfileNotAvailableError\n",
      "        ExtractionError\n",
      "        VariableError\n",
      "    NameError\n",
      "        UnboundLocalError\n",
      "    AttributeError\n",
      "        FrozenInstanceError\n",
      "    SyntaxError\n",
      "        IndentationError\n",
      "            TabError\n",
      "    LookupError\n",
      "        IndexError\n",
      "        KeyError\n",
      "            NoSuchKernel\n",
      "            UnknownBackend\n",
      "        CodecRegistryError\n",
      "    ValueError\n",
      "        UnicodeError\n",
      "            UnicodeEncodeError\n",
      "            UnicodeDecodeError\n",
      "            UnicodeTranslateError\n",
      "        UnsupportedOperation\n",
      "        JSONDecodeError\n",
      "        SSLCertVerificationError\n",
      "        Error\n",
      "        UnsupportedDigestmodError\n",
      "        IllegalMonthError\n",
      "        IllegalWeekdayError\n",
      "        ParserError\n",
      "        ClassNotFound\n",
      "        ClipboardEmpty\n",
      "        MessageDefect\n",
      "            NoBoundaryInMultipartDefect\n",
      "            StartBoundaryNotFoundDefect\n",
      "            CloseBoundaryNotFoundDefect\n",
      "            FirstHeaderLineIsContinuationDefect\n",
      "            MisplacedEnvelopeHeaderDefect\n",
      "            MissingHeaderBodySeparatorDefect\n",
      "            MultipartInvariantViolationDefect\n",
      "            InvalidMultipartContentTransferEncodingDefect\n",
      "            UndecodableBytesDefect\n",
      "            InvalidBase64PaddingDefect\n",
      "            InvalidBase64CharactersDefect\n",
      "            InvalidBase64LengthDefect\n",
      "            HeaderDefect\n",
      "                InvalidHeaderDefect\n",
      "                HeaderMissingRequiredValue\n",
      "                NonPrintableDefect\n",
      "                ObsoleteHeaderDefect\n",
      "                NonASCIILocalPartDefect\n",
      "                InvalidDateDefect\n",
      "        MacroToEdit\n",
      "        InvalidFileException\n",
      "        UnequalIterablesError\n",
      "        InvalidVersion\n",
      "        _InvalidELFFileHeader\n",
      "        InvalidWheelFilename\n",
      "        InvalidSdistFilename\n",
      "        InvalidSpecifier\n",
      "        InvalidMarker\n",
      "        UndefinedComparison\n",
      "        UndefinedEnvironmentName\n",
      "        InvalidRequirement\n",
      "            RequirementParseError\n",
      "        InvalidVersion\n",
      "    AssertionError\n",
      "    ArithmeticError\n",
      "        FloatingPointError\n",
      "        OverflowError\n",
      "        ZeroDivisionError\n",
      "            DivisionByZero\n",
      "            DivisionUndefined\n",
      "        DecimalException\n",
      "            Clamped\n",
      "            Rounded\n",
      "                Underflow\n",
      "                Overflow\n",
      "            Inexact\n",
      "                Underflow\n",
      "                Overflow\n",
      "            Subnormal\n",
      "                Underflow\n",
      "            DivisionByZero\n",
      "            FloatOperation\n",
      "            InvalidOperation\n",
      "                ConversionSyntax\n",
      "                DivisionImpossible\n",
      "                DivisionUndefined\n",
      "                InvalidContext\n",
      "    SystemError\n",
      "        CodecRegistryError\n",
      "    ReferenceError\n",
      "    MemoryError\n",
      "    BufferError\n",
      "    Warning\n",
      "        UserWarning\n",
      "            GetPassWarning\n",
      "            FormatterWarning\n",
      "        EncodingWarning\n",
      "        DeprecationWarning\n",
      "            ProvisionalWarning\n",
      "        PendingDeprecationWarning\n",
      "        SyntaxWarning\n",
      "        RuntimeWarning\n",
      "            ProactorSelectorThreadWarning\n",
      "            UnknownTimezoneWarning\n",
      "            PEP440Warning\n",
      "        FutureWarning\n",
      "            ProvisionalCompleterWarning\n",
      "        ImportWarning\n",
      "        UnicodeWarning\n",
      "        BytesWarning\n",
      "        ResourceWarning\n",
      "        DeprecatedTzFormatWarning\n",
      "        PkgResourcesDeprecationWarning\n",
      "    _OptionError\n",
      "    _Error\n",
      "    error\n",
      "    Verbose\n",
      "    Error\n",
      "    SubprocessError\n",
      "        CalledProcessError\n",
      "        TimeoutExpired\n",
      "    TokenError\n",
      "    StopTokenizing\n",
      "    ClassFoundException\n",
      "    EndOfBlock\n",
      "    TraitError\n",
      "    Error\n",
      "    Error\n",
      "        CancelledError\n",
      "        TimeoutError\n",
      "        InvalidStateError\n",
      "    _GiveupOnSendfile\n",
      "    error\n",
      "    Incomplete\n",
      "    TimeoutError\n",
      "    InvalidStateError\n",
      "    LimitOverrunError\n",
      "    QueueEmpty\n",
      "    QueueFull\n",
      "    Empty\n",
      "    Full\n",
      "    ArgumentError\n",
      "    ZMQBaseError\n",
      "        ZMQError\n",
      "            ContextTerminated\n",
      "            Again\n",
      "            InterruptedSystemCall\n",
      "        ZMQBindError\n",
      "        NotDone\n",
      "    PickleError\n",
      "        PicklingError\n",
      "        UnpicklingError\n",
      "    _Stop\n",
      "    ArgumentError\n",
      "    ArgumentTypeError\n",
      "    ConfigError\n",
      "        ConfigLoaderError\n",
      "            ArgumentError\n",
      "        ConfigFileNotFound\n",
      "    ConfigurableError\n",
      "        MultipleInstanceError\n",
      "    ApplicationError\n",
      "    error\n",
      "    TimeoutError\n",
      "    error\n",
      "    ReturnValueIgnoredError\n",
      "    KeyReuseError\n",
      "    UnknownKeyError\n",
      "    LeakedCallbackError\n",
      "    BadYieldError\n",
      "    ReturnValueIgnoredError\n",
      "    Return\n",
      "    InvalidPortNumber\n",
      "    error\n",
      "    LZMAError\n",
      "    RegistryError\n",
      "    _GiveupOnFastCopy\n",
      "    Error\n",
      "        NoSectionError\n",
      "        DuplicateSectionError\n",
      "        DuplicateOptionError\n",
      "        NoOptionError\n",
      "        InterpolationError\n",
      "            InterpolationMissingOptionError\n",
      "            InterpolationSyntaxError\n",
      "            InterpolationDepthError\n",
      "        ParsingError\n",
      "            MissingSectionHeaderError\n",
      "    NoIPAddresses\n",
      "    BadZipFile\n",
      "    LargeZipFile\n",
      "    BadEntryPoint\n",
      "    NoSuchEntryPoint\n",
      "    DuplicateKernelError\n",
      "    ErrorDuringImport\n",
      "    NotOneValueFound\n",
      "    CannotEval\n",
      "    OptionError\n",
      "    BdbQuit\n",
      "    Restart\n",
      "    ExceptionPexpect\n",
      "        EOF\n",
      "        TIMEOUT\n",
      "    PtyProcessError\n",
      "    FindCmdError\n",
      "    HomeDirError\n",
      "    ProfileDirError\n",
      "    IPythonCoreError\n",
      "        TryNext\n",
      "        UsageError\n",
      "        StdinNotImplementedError\n",
      "    InputRejected\n",
      "    GetoptError\n",
      "    ErrorToken\n",
      "    PrefilterError\n",
      "    AliasError\n",
      "        InvalidAliasError\n",
      "    Error\n",
      "        InterfaceError\n",
      "        DatabaseError\n",
      "            InternalError\n",
      "            OperationalError\n",
      "            ProgrammingError\n",
      "            IntegrityError\n",
      "            DataError\n",
      "            NotSupportedError\n",
      "    Warning\n",
      "    SpaceInInput\n",
      "    DOMException\n",
      "        IndexSizeErr\n",
      "        DomstringSizeErr\n",
      "        HierarchyRequestErr\n",
      "        WrongDocumentErr\n",
      "        InvalidCharacterErr\n",
      "        NoDataAllowedErr\n",
      "        NoModificationAllowedErr\n",
      "        NotFoundErr\n",
      "        NotSupportedErr\n",
      "        InuseAttributeErr\n",
      "        InvalidStateErr\n",
      "        SyntaxErr\n",
      "        InvalidModificationErr\n",
      "        NamespaceErr\n",
      "        InvalidAccessErr\n",
      "        ValidationErr\n",
      "    ValidationError\n",
      "    EditReadOnlyBuffer\n",
      "    _Retry\n",
      "    InvalidLayoutError\n",
      "    HeightIsUnknownError\n",
      "    ParserSyntaxError\n",
      "    InternalParseError\n",
      "    _PositionUpdatingFinished\n",
      "    SimpleGetItemNotFound\n",
      "    UncaughtAttributeError\n",
      "    HasNoContext\n",
      "    ParamIssue\n",
      "    _JediError\n",
      "        InternalError\n",
      "        WrongVersion\n",
      "        RefactoringError\n",
      "    OnErrorLeaf\n",
      "    InvalidPythonEnvironment\n",
      "    MessageError\n",
      "        MessageParseError\n",
      "            HeaderParseError\n",
      "            BoundaryError\n",
      "        MultipartConversionError\n",
      "        CharsetError\n",
      "    Error\n",
      "    HTTPException\n",
      "        NotConnected\n",
      "        InvalidURL\n",
      "        UnknownProtocol\n",
      "        UnknownTransferEncoding\n",
      "        UnimplementedFileMode\n",
      "        IncompleteRead\n",
      "        ImproperConnectionState\n",
      "            CannotSendRequest\n",
      "            CannotSendHeader\n",
      "            ResponseNotReady\n",
      "        BadStatusLine\n",
      "            RemoteDisconnected\n",
      "        LineTooLong\n",
      "    InteractivelyDefined\n",
      "    KillEmbedded\n",
      "    Error\n",
      "        NoSuchProcess\n",
      "            ZombieProcess\n",
      "        AccessDenied\n",
      "        TimeoutExpired\n",
      "    _Ipv6UnsupportedError\n",
      "    QueueEmpty\n",
      "    QueueFull\n",
      "    DebuggerInitializationError\n",
      "    ExpatError\n",
      "    Error\n",
      "        ProtocolError\n",
      "        ResponseError\n",
      "        Fault\n",
      "    ParseBaseException\n",
      "        ParseException\n",
      "        ParseFatalException\n",
      "            ParseSyntaxException\n",
      "    RecursiveGrammarException\n",
      "    ResolutionError\n",
      "        VersionConflict\n",
      "            ContextualVersionConflict\n",
      "        DistributionNotFound\n",
      "        UnknownExtra\n",
      "    _Error\n",
      "    UnableToResolveVariableException\n",
      "    InvalidTypeInArgsException\n"
     ]
    }
   ],
   "source": [
    "# 2nd-\n",
    "def print_exception_hierarchy(exception_class, indent=0):\n",
    "    print(' ' * indent + exception_class.__name__)\n",
    "    for subclass in exception_class.__subclasses__():\n",
    "        print_exception_hierarchy(subclass, indent + 4)\n",
    "\n",
    "# Print the Exception Hierarchy\n",
    "print_exception_hierarchy(Exception)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "f093a54e-dc13-4998-9df8-0d832f072cfc",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error: division by zero\n"
     ]
    }
   ],
   "source": [
    "# 3rd-\n",
    "''' The ArithmeticError class in Python is the base class for exceptions that occur during arithmetic operations. It \n",
    "serves as a parent class for several specific arithmetic-related exceptions. Here are two commonly used exceptions\n",
    "derived from ArithmeticError along with their explanations and examples:\n",
    "\n",
    "ZeroDivisionError: This exception is raised when attempting to divide a number by zero '''\n",
    "\n",
    "try:\n",
    "    result = 10 / 0  # Division by zero\n",
    "except ZeroDivisionError as e:\n",
    "    print(\"Error:\", str(e))\n",
    "\n",
    "    \n",
    "''' In this example, dividing 10 by 0 raises a ZeroDivisionError. The exception is caught in the except block, and the\n",
    "error message \"Error: division by zero\" is printed.\n",
    "\n",
    "OverflowError: This exception is raised when the result of an arithmetic operation exceeds the maximum \n",
    "representable value.'''\n",
    "\n",
    "try:\n",
    "    result = 2 ** 1000  # Exponentiation resulting in an overflow\n",
    "except OverflowError as e:\n",
    "    print(\"Error:\", str(e))\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "b38770d2-9bb5-48b7-b4e5-65d19f8c6906",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error: 'address'\n",
      "Error: list index out of range\n"
     ]
    }
   ],
   "source": [
    "# 4th-\n",
    "''' The LookupError class in Python is the base class for exceptions that occur when a lookup or indexing operation\n",
    "fails. It serves as a parent class for several specific lookup-related exceptions. Here are two commonly used \n",
    "exceptions derived from LookupError along with their explanations and examples:\n",
    "\n",
    "KeyError: This exception is raised when a dictionary key or a set element is not found during a lookup operation. '''\n",
    "\n",
    "my_dict = {\"name\": \"John\", \"age\": 30}\n",
    "\n",
    "try:\n",
    "    value = my_dict[\"address\"]  # Lookup for a non-existent key\n",
    "except KeyError as e:\n",
    "    print(\"Error:\", str(e))\n",
    "\n",
    "    \n",
    "''' In this example, we attempt to access the value associated with the key \"address\" in the my_dict dictionary using square\n",
    "brackets ([]). Since the key \"address\" does not exist in the dictionary, a KeyError is raised. The exception is \n",
    "caught in the except block, and the error message \"Error: 'address'\" is printed.\n",
    "\n",
    "IndexError: This exception is raised when an index for a sequence (such as a list or a string) is out of range or \n",
    "not found.'''\n",
    "\n",
    "my_list = [1, 2, 3]\n",
    "\n",
    "try:\n",
    "    value = my_list[5]  # Accessing an out-of-range index\n",
    "except IndexError as e:\n",
    "    print(\"Error:\", str(e))\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "a4915bfc-d90f-4be7-bd9d-a9196d5749e0",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "' \\nImportError is an exception class in Python that is raised when an import statement fails to import a module. It \\nserves as the base class for various import-related exceptions. This exception is commonly encountered when there \\nare issues with importing modules or resolving dependencies in Python code.\\n\\nModuleNotFoundError is a specific exception that is derived from ImportError. It is raised when a module cannot be\\nfound or imported. '"
      ]
     },
     "execution_count": 5,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# 5th-\n",
    "''' \n",
    "ImportError is an exception class in Python that is raised when an import statement fails to import a module. It \n",
    "serves as the base class for various import-related exceptions. This exception is commonly encountered when there \n",
    "are issues with importing modules or resolving dependencies in Python code.\n",
    "\n",
    "ModuleNotFoundError is a specific exception that is derived from ImportError. It is raised when a module cannot be\n",
    "found or imported. '''"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "5676605d-7afd-436a-b092-b935a5eefe9e",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "' Certainly! Here are some best practices for exception handling in Python:\\n\\nBe specific with exception handling: Catch only the exceptions you expect and can handle. Avoid using broad\\nexception handlers like catching Exception unless you have a valid reason. This helps in accurately identifying\\nand handling specific error scenarios.\\n\\nUse multiple except blocks: Handle different exceptions separately using multiple except blocks. This allows you \\nto provide specific error handling logic for each type of exception.\\n\\nHandle exceptions gracefully: Handle exceptions in a way that provides useful information to users or logs, without\\nrevealing sensitive information. Consider logging the exception details and providing user-friendly error messages.\\n\\nUse try-except-else construct: Utilize the else block in try-except statements to execute code that should only \\nrun if no exceptions are raised. This helps separate the exception handling logic from the regular code flow.\\n\\nAvoid bare except statements: Avoid using bare except statements without specifying the exception type. It can \\nmask errors and make debugging difficult. Always be explicit about the exceptions you are catching.\\n\\nUse finally block for cleanup: When necessary, use the finally block to ensure that cleanup code, such as closing \\nfiles or releasing resources, is always executed, regardless of whether an exception was raised or not.\\n\\nReraise exceptions selectively: If you catch an exception but cannot handle it appropriately, consider reraising \\nthe exception using raise without any arguments. This allows the exception to propagate up the call stack for \\nhigher-level handlers to handle.\\n\\nConsider creating custom exceptions: Create custom exception classes when you have specific error conditions or \\nexceptional situations in your code. This helps in organizing your exception hierarchy and provides meaningful\\nerror messages.\\n\\nKeep exception handling code separate: Separate exception handling code from regular code to improve readability \\nand maintainability. Avoid mixing exception handling with the main logic of your program.\\n\\nTest exception handling: Write test cases specifically targeting exception handling to ensure that exceptions are \\nraised, caught, and handled as expected. This helps in verifying the correctness of your exception handling code.\\n\\nBy following these best practices, you can write robust and maintainable code with effective exception handling in \\nPython. '"
      ]
     },
     "execution_count": 6,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# 6th-\n",
    "''' Certainly! Here are some best practices for exception handling in Python:\n",
    "\n",
    "Be specific with exception handling: Catch only the exceptions you expect and can handle. Avoid using broad\n",
    "exception handlers like catching Exception unless you have a valid reason. This helps in accurately identifying\n",
    "and handling specific error scenarios.\n",
    "\n",
    "Use multiple except blocks: Handle different exceptions separately using multiple except blocks. This allows you \n",
    "to provide specific error handling logic for each type of exception.\n",
    "\n",
    "Handle exceptions gracefully: Handle exceptions in a way that provides useful information to users or logs, without\n",
    "revealing sensitive information. Consider logging the exception details and providing user-friendly error messages.\n",
    "\n",
    "Use try-except-else construct: Utilize the else block in try-except statements to execute code that should only \n",
    "run if no exceptions are raised. This helps separate the exception handling logic from the regular code flow.\n",
    "\n",
    "Avoid bare except statements: Avoid using bare except statements without specifying the exception type. It can \n",
    "mask errors and make debugging difficult. Always be explicit about the exceptions you are catching.\n",
    "\n",
    "Use finally block for cleanup: When necessary, use the finally block to ensure that cleanup code, such as closing \n",
    "files or releasing resources, is always executed, regardless of whether an exception was raised or not.\n",
    "\n",
    "Reraise exceptions selectively: If you catch an exception but cannot handle it appropriately, consider reraising \n",
    "the exception using raise without any arguments. This allows the exception to propagate up the call stack for \n",
    "higher-level handlers to handle.\n",
    "\n",
    "Consider creating custom exceptions: Create custom exception classes when you have specific error conditions or \n",
    "exceptional situations in your code. This helps in organizing your exception hierarchy and provides meaningful\n",
    "error messages.\n",
    "\n",
    "Keep exception handling code separate: Separate exception handling code from regular code to improve readability \n",
    "and maintainability. Avoid mixing exception handling with the main logic of your program.\n",
    "\n",
    "Test exception handling: Write test cases specifically targeting exception handling to ensure that exceptions are \n",
    "raised, caught, and handled as expected. This helps in verifying the correctness of your exception handling code.\n",
    "\n",
    "By following these best practices, you can write robust and maintainable code with effective exception handling in \n",
    "Python. '''"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a4d2f7a2-a30e-47b9-b839-c54b4f59fbcc",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
